# Use the official Node.js image as the base image
FROM node:20

# Set the working directory
WORKDIR /app/backend

# Copy the package.json and package-lock.json to the working directory
COPY package*.json ./

# Install the dependencies
RUN npm install

# Copy the rest of the application source code
COPY . .

# Expose the port the app runs on (change to your backend port)
EXPOSE 5000

# Start the backend server
CMD ["node", "index.js"]
